boundaries:
  dataset: "unmap-international-boundaries-1m"
  dataset_exceptions:
    MMR: "mimu-geonode-myanmar-state-and-region-boundaries-mimu"
    JOR: "geoboundaries-admin-boundaries-for-jordan"
  resource_exceptions:
    HND: "hnd_adm_sinit_20161005_SHP.zip"
    LBN: "lbn_adm_cdr_20200810.zip"
    MMR: "Myanmar State and Region Boundaries MIMU v9.3 shapefile"
    MOZ: "moz_adm_20190607b_SHP.zip"
    SYR: "SYR Administrative Divisions Shapefiles.zip"

health_facilities:
  dataset: "admin-1-health-facilities-for-data-explorers"
  dataset_exceptions:
    NER: "hotosm_niger_health_facilities"

population:
  dataset: "admin-1-population-statistics-for-data-explorers"

mapbox:
  global:
    adm1-polbnda: "cl2qdtczb0chh28lhq82qor46"
    adm1-polbndl: "cl2qdzdzl19gr28r04iabhfs7"
    adm1-centroid: "cl2qdtxar0hwd29tkct32yp5a"
    adm0-polbnda: "cl2qdreq4003128mppop3aidz"
    adm0-polbndl: "cl2qdzz3p093827mm46l6ojzx"
    adm0-centroid: "cl2qdugrr5e1r27t85am5vsgr"
    lakes: "cl2qcnlcg002v28lnpi69l0rs"
  covid:
    adm1-polbnda: "humdata.b1o0ci53"
    adm1-polbndl: "humdata.1a2n5p4n"
    adm1-centroid: "humdata.63k3lb2z"
    adm0-polbnda: "humdata.5qlwwz0l"
    adm0-polbndl: "humdata.bkhifgb5"
    adm0-centroid: "humdata.4w8b1b7g"
  arab-states:
    adm1-polbnda: "humdata.attm70id"
    adm1-polbndl: "humdata.6tv02ole"
    adm1-centroid: "humdata.8pyb1abd"
    adm0-polbnda: "humdata.aioadufm"
    adm0-polbndl: "humdata.bzo5ss37"
    adm0-centroid: "humdata.d4ywfeza"
  ukraine:
    adm1-polbnda: "humdata.7mw1qwu2"
    adm1-polbndl: "humdata.afes2yub"
    adm1-centroid: "humdata.b2dsq510"
    adm0-polbnda: "humdata.090db5y9"
    adm0-polbndl: "humdata.8lxpktpe"
    adm0-centroid: "humdata.av64hwpt"

adm1:
  covid:
    - AFG
    - BDI
    - BFA
    - CAF
    - CMR
    - COD
    - COL
    - ETH
    - GTM
    - HND
    - HTI
    - IRQ
    - LBY
    - MLI
    - MMR
    - MOZ
    - NER
    - NGA
    - PSE
    - SDN
    - SLV
    - SOM
    - SSD
    - SYR
    - TCD
    - UKR
    - VEN
    - YEM
  arab-states:
    - ARE
    - BHR
    - COM
    - DJI
    - DZA
    - EGY
    - IRQ
    - JOR
    - KWT
    - LBN
    - LBY
    - MAR
    - MRT
    - OMN
    - PSE
    - QAT
    - SAU
    - SDN
    - SOM
    - SYR
    - TUN
    - YEM
  ukraine:
    - UKR

adm0:
  covid:
    - ABW
    - AFG
    - AGO
    - ARG
    - BDI
    - BFA
    - BGD
    - BOL
    - BRA
    - CAF
    - CHL
    - CMR
    - COD
    - COG
    - COL
    - CRI
    - CUW
    - DJI
    - DOM
    - ECU
    - EGY
    - ETH
    - GTM
    - GUY
    - HND
    - HTI
    - IRN
    - IRQ
    - JOR
    - KEN
    - LBN
    - LBY
    - MDG
    - MEX
    - MLI
    - MMR
    - MOZ
    - NER
    - NGA
    - PAK
    - PAN
    - PER
    - PRY
    - PSE
    - RWA
    - SDN
    - SLV
    - SOM
    - SSD
    - SYR
    - TCD
    - TJK
    - TKM
    - TTO
    - TUR
    - TZA
    - UGA
    - UKR
    - URY
    - UZB
    - VEN
    - YEM
    - ZMB
  arab-states:
    - ARE
    - BHR
    - COM
    - DJI
    - DZA
    - EGY
    - IRQ
    - JOR
    - KWT
    - LBN
    - LBY
    - MAR
    - MRT
    - OMN
    - PSE
    - QAT
    - SAU
    - SDN
    - SOM
    - SYR
    - TUN
    - YEM
  ukraine:
    - BLR
    - HUN
    - MDA
    - POL
    - ROU
    - SVK
    - UKR

shapefile_attribute_mappings:
  pcode:
    - "ADM1_PCODE"
    - "ADM1_CODE"
    - "ADM1_ID"
    - "ADMIN1PCOD"
    - "ID_1"
    - "ST_PCODE"
  name:
    - "ADM1_NAME"
    - "ADM1_EN"
    - "ADM1_ES"
    - "ADM1_FR"
    - "ADM1_PT"
    - "ADMIN1NAME"
    - "NAME_1"
    - "ST"
    - "shapeName"

regional:
  format: "xlsx"
  dataset: "unocha-office-locations"
  sheet: 1
  headers: 1
  iso3: "ISO3"
  region: "Regional_office"
